<?php  namespace RegistrarBundle\Repository;


use Doctrine\ORM\EntityRepository;
use RegistrarBundle\Entity\RegistrationApplication;

/**
 * RegistrationApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationApplicationRepository extends EntityRepository
{
    /**
     * @param string $email
     * @param string|null $ticket
     * @return RegistrationApplication|null
     */
    public function getUnexpired($email, $ticket = null)
    {
        $now = new \DateTime();

        $queryBuilder = $this->createQueryBuilder('t');
        $queryBuilder->where('t.expireAt > :now');
        $queryBuilder->andWhere('t.email = :email');

        $queryBuilder->setParameter('now', $now);
        $queryBuilder->setParameter('email', $email);

        if ($ticket) {
            $queryBuilder->andWhere('t.ticket = :ticket')->setParameter('ticket', $ticket);
        }

        $query = $queryBuilder->getQuery();

        return $query->getOneOrNullResult();
    }

    /**
     * @return array
     */
    public function getExpired()
    {
        $now = new \DateTime();

        $queryBuilder = $this->createQueryBuilder('t');
        $queryBuilder->where('t.expireAt <= :now');
        $queryBuilder->orWhere('t.expireAt IS NULL');

        $queryBuilder->setParameter('now', $now);

        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }
}
